name: CI - Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies (workspace)
        run: npm install

      - name: Build Web
        run: npm run build -w @cb/web

      - name: Build API
        run: npm run build -w @cb/api
